apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_ENVIRONMENT: "Development"

  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "123456"

  AUDIT_CONNECTION: "Host=postgres;Port=5432;Database=auditdb;Username=postgres;Password=123456"
  IDENTITY_CONNECTION: "Host=postgres;Port=5432;Database=identitydb;Username=postgres;Password=123456"
  ELECTION_CONNECTION: "Host=postgres;Port=5432;Database=electiondb;Username=postgres;Password=123456"
  TALLY_CONNECTION: "Host=postgres;Port=5432;Database=tallydb;Username=postgres;Password=123456"
  VOTE_CASTING_CONNECTION: "Host=postgres;Port=5432;Database=vote_castingdb;Username=postgres;Password=123456"
  VOTER_REGISTRY_CONNECTION: "Host=postgres;Port=5432;Database=voter_registrydb;Username=postgres;Password=123456"
