apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  db_init.sql: |
    CREATE DATABASE "auditdb";
    CREATE DATABASE "identitydb";
    CREATE DATABASE "electiondb";
    CREATE DATABASE "tallydb";
    CREATE DATABASE "vote_castingdb";
    CREATE DATABASE "voter_registrydb";
